### ISSUE TITLE
List posts by tags (inc seasons) 

### ISSUE THREAD

**Issue by si** [si/mlw#31]
All episode content has multiple tags set including the season number e.g. `season-1` or `season-2`
List posts based on the tag so season-1 returns all 5 episodes for S01
URLs should use the prefix `/tag/` e.g. `/tag/season-1/`

**Comment by mikestreety** [comment]
@si you need to make a "tag.njk" (or whatever page format you're using) to use a template:

https://gitlab.com/mikestreety/mikestreety/-/blob/main/app/content/category.njk

It then uses `eleventyComputed` and the `pagination` to auto create all the pages. It will then make a "tag" page for every tag used

**Comment by mikestreety** [comment]
I also do it on Ale House Rock with less code 😄 

https://gitlab.com/mikestreety-sites/ale-house-rock/-/blob/main/app/content/category.njk (which results in https://alehouse.rocks/category/paleale/)

I have an idea to make nicer landing pages and to map `paleale` to `Pale Ale` so I can control the tag more

**Comment by si** [comment]
Looking good: https://wondrous-faun-019cfd.netlify.app/tag/season-1/
